### ISSUE TITLE
limited upload size from php.ini, should be included in the build step

### ISSUE THREAD

**Issue by kristian-94** [catalyst/docker_moodle_builder#5]
We need these settings added to php.ini for moodle to handle large uploads:

upload_max_filesize = 8000M
post_max_size = 8000M

according to https://docs.moodle.org/38/en/File_upload_size#Upload_file_size_restrictions

**Comment by kenneth-hendricks** [comment]
Closing as fixed in https://github.com/catalyst/docker_moodle_builder/pull/6
